# Generated by Django 4.2.11 on 2026-05-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('id_livro', models.CharField(blank=True, max_length=50, null=True)),
                ('id_emprestimo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('reserva', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emprestimo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('isbn_13', models.CharField(blank=True, max_length=13, null=True)),
                ('isbn_10', models.CharField(blank=True, max_length=10, null=True)),
                ('editora', models.CharField(blank=True, max_length=255, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('paginas', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=255, null=True)),
                ('status_livro', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'livros',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('privilegio', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
    ]
