# Generated by Django 4.2.11 on 2026-05-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emprestimo_livros_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_loans_per_reader', models.PositiveIntegerField(default=2, help_text='Máximo de empréstimos por leitor')),
                ('max_overdue_days', models.PositiveIntegerField(default=7, help_text='Máximo de dias em atraso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Empréstimos',
                'verbose_name_plural': 'Configurações de Empréstimos',
            },
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
