# Generated by Django 4.2.11 on 2026-05-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loanconfig_alter_emprestimo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='overdue_days',
            field=models.PositiveIntegerField(default=7, help_text='Dias de tolerância para atraso (armazenado na criação do empréstimo)'),
        ),
    ]
