# Generated by Django 4.2.11 on 2026-05-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emprestimo_overdue_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='reserva',
        ),
    ]
