# Generated by Django 4.2.11 on 2026-05-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_emprestimo_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanconfig',
            name='loan_duration_days',
            field=models.PositiveIntegerField(default=7, help_text='Duração do empréstimo em dias'),
        ),
    ]
