# Generated by Django 4.2.9 on 2026-06-11 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_status_damagereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegularization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('financial', 'Reembolso financeiro'), ('replacement', 'Substituição do livro'), ('other', 'Outro')], help_text='Método usado para regularizar a situação', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Observações adicionais sobre a regularização', max_length=500, null=True)),
                ('regularized_at', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(help_text='Administrador que realizou a regularização', on_delete=django.db.models.deletion.CASCADE, related_name='performed_regularizations', to=settings.AUTH_USER_MODEL)),
                ('damage_report', models.OneToOneField(help_text='Relatório de dano que está sendo regularizado', on_delete=django.db.models.deletion.CASCADE, related_name='regularization', to='accounts.damagereport')),
                ('user', models.ForeignKey(help_text='Usuário que estava bloqueado', on_delete=django.db.models.deletion.CASCADE, related_name='regularizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regularização de Usuário',
                'verbose_name_plural': 'Regularizações de Usuários',
                'ordering': ['-regularized_at'],
            },
        ),
    ]